### ISSUE TITLE
CK/CSの記述場所の変更

### ISSUE THREAD

**Issue by masawada** [WhiteHawk-taka/ShirotakaTwit_for_FirefoxOS#15]
Consumer Key/Consumer Secretを`js/app.js`の中にハードコードするとforkして書き換えてcommit, pushする人が出てくる可能性がある(ないと思うけど…)。
それでなくともどこにあるのかわかりづらいので`keys.js`とかに書いて`.gitignore`でignoreしておくべき。

**Comment by WhiteHawk-taka** [comment]
キーファイル作成

**Comment by WhiteHawk-taka** [comment]
key.txtを作ることによりキーファイルの除外に成功
